spring.application.name=service-auth
# MySQL Configuration
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/auth_service?createDatabaseIfNotExist=true
spring.datasource.username=${dbuser}
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


jwt.secret=your-very-secure-secret-key-at-least-256-bits-long
jwt.expiration=86400   


logging.level.com.location.voitures=DEBUG
logging.level.org.springframework.security=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Optional: Health Check (for Eureka monitoring)
management.endpoints.web.exposure.include=health,info

eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15
eureka.server.enable-self-preservation=false


spring.config.import=optional:configserver:http://localhost:8888





spring.kafka.bootstrap-servers=192.168.255.110:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
kafka.order.topic=Client-Welcome
