server.port=8222
spring.application.name=gateway-service

# Eureka connection
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Discovery locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Manual routes (optional if you want specific paths)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://service-auth
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Your agence route
spring.cloud.gateway.routes[1].id=agence-service
spring.cloud.gateway.routes[1].uri=lb://service-agence
spring.cloud.gateway.routes[1].predicates[0]=Path=/agence/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/agence/(?<segment>.*), /$\{segment}


spring.cloud.gateway.routes[2].id=client-service
spring.cloud.gateway.routes[2].uri=lb://service-client
spring.cloud.gateway.routes[2].predicates[0]=Path=/client/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/client/(?<segment>.*), /$\{segment}


logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG
